'use client';
import {useEffect, useMemo, useState} from 'react';

type Price={dam:number|null;rt:number|null;spread:number|null;rt_intervals:number;complete:boolean};
type Hour={time:string;label:string;load:number|null;wind:number|null;solar:number|null;load_forecast:number|null;wind_forecast:number|null;solar_forecast:number|null;load_outlook:number|null;wind_outlook:number|null;solar_outlook:number|null;net_load:number|null;net_load_forecast:number|null;load_error:number|null;wind_error:number|null;solar_error:number|null;net_load_error:number|null;basis:number|null;prices:Record<string,Price>;forecast_issued:Record<string,string|null>};
type Reading={value:number|null;time:string|null;unit:string;source:string|null};
type Source={name:string;url:string;status:string;records:number;updated?:string;checked:string;message?:string};
type Event={time:string;label:string;type:string;value:number;unit:string;threshold:number};
type Weather={city:string;actual:Record<string,Reading>;forecast:({time:string}&Record<string,number|string>)[]};
type Snapshot={published_at:string;hours:Hour[];current:Record<string,Reading>;hubs:({hub:string;dam:number|null;spread:number|null;interval_minutes:number|null}&Reading)[];storage:({time:string}&Record<string,number|string>)[];generation:{fuel:string;value:number;time:string}[];weather:Weather[];events:Event[];sources:Source[];archive_records:number;methodology:Record<string,string>};
type Summary={days:number;complete_price_hours:number;observed_load_hours:number;average_rt:number|null;max_rt:number|null;peak_load:number|null;net_load_mae:number|null;forecast_comparison_hours:number;events:number};
type Report={title:string;published_at:string;daily:Summary;weekly:Summary;events:Event[];sources:Source[];methodology:Record<string,string>};
type Edition={edition:string;file:string;published_at:string};
type Datum={time:string;[key:string]:number|string|null};
type Series={key:string;label:string;color:string;dash?:boolean};
const BASE=process.env.NEXT_PUBLIC_BASE_PATH||'';
const money=(n:number|null|undefined)=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const num=(n:number|null|undefined,digits=1)=>n==null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:digits}).format(n);
const ct=(t:string|null|undefined,full=false)=>t?new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',...(full?{timeZoneName:'short' as const}:{})}).format(new Date(t)):'Unavailable';
const signed=(n:number|null|undefined,digits=1)=>n==null?'—':`${n>0?'+':''}${num(n,digits)}`;
const colors={green:'#6ee7b7',blue:'#7cb7ff',orange:'#ffb46b',pink:'#ec9abf',purple:'#b7a5fc'};
const views=[['overview','Market overview'],['prices','Prices & basis'],['forecasts','Forecast monitor'],['weather','Weather'],['storage','Energy storage'],['reports','Reports & archive'],['sources','Data & methods']] as const;
type View=typeof views[number][0];
function Icon({name}:{name:string}){const paths:Record<string,string>={overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',prices:'M3 17l5-6 4 3 8-10 M16 4h4v4',forecasts:'M3 18h18 M5 14l4-7 5 6 5-9',weather:'M7 16a5 5 0 1 1 9-4 4 4 0 0 1 1 8H7a4 4 0 0 1 0-8 M8 2v2 M2 8h2',storage:'M4 7h15v12H4z M19 11h2v4h-2 M11 9l-3 5h4l-2 3',reports:'M5 3h10l4 4v14H5z M14 3v5h5 M8 12h8 M8 16h6',sources:'M12 3l9 5-9 5-9-5z M3 12l9 5 9-5 M3 16l9 5 9-5',refresh:'M20 7v5h-5 M20 12a8 8 0 1 0-2 6',arrow:'M5 12h14 M14 7l5 5-5 5',download:'M12 3v12 M7 10l5 5 5-5 M4 17v4h16v-4'};return <svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.overview}/></svg>}
function Chart({title,subtitle,data,series,unit='GW',scale=1000}:{title:string;subtitle?:string;data:Datum[];series:Series[];unit?:string;scale?:number}){
 const [hover,setHover]=useState<number|null>(null); const W=840,H=255,L=53,R=18,T=15,B=35;
 const vals=data.flatMap(r=>series.map(s=>r[s.key]).filter((v):v is number=>typeof v==='number'&&Number.isFinite(v))).map(v=>v/scale);
 const min=vals.length?Math.min(...vals):0,max=vals.length?Math.max(...vals):1;
 const pad=Math.max((max-min)*.14,1);const lo=min-pad,hi=max+pad;
 const ts=data.map(d=>new Date(d.time).getTime()),first=ts[0]||0,last=ts[ts.length-1]||1;
 const x=(i:number)=>L+(W-L-R)*(ts[i]-first)/(last-first||1),y=(v:number)=>T+(H-T-B)*(1-(v/scale-lo)/(hi-lo));
 const path=(key:string)=>{let pen=false;return data.map((r,i)=>{const v=r[key];if(typeof v!=='number'){pen=false;return ''}const p=`${pen?'L':'M'}${x(i).toFixed(1)},${y(v).toFixed(1)}`;pen=true;return p}).join(' ')};
 const item=hover!=null?data[hover]:null;
 return <section className="panel chart-panel"><div className="panel-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><span className="unit">{unit}</span></div>
 <div className="chart" onMouseLeave={()=>setHover(null)}>
 {vals.length?<svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label={`${title}. ${data.length} time intervals. Values in ${unit}.`} onMouseMove={e=>{const rect=e.currentTarget.getBoundingClientRect();const px=(e.clientX-rect.left)*W/rect.width;let closest=0;for(let i=1;i<data.length;i++)if(Math.abs(x(i)-px)<Math.abs(x(closest)-px))closest=i;setHover(closest)}}>
 <title>{title}</title><desc>{subtitle} Missing observations appear as gaps.</desc>
 {[0,1,2,3,4].map(i=>{const v=lo+(hi-lo)*i/4;const py=y(v*scale);return <g key={i}><line x1={L} x2={W-R} y1={py} y2={py} stroke="#243043" strokeDasharray="3 5"/><text x={L-10} y={py+4} textAnchor="end" fill="#8190a4" fontSize="11">{num(v,0)}</text></g>})}
 {series.map(s=><path key={s.key} d={path(s.key)} fill="none" stroke={s.color} strokeWidth="2.2" strokeDasharray={s.dash?'5 5':undefined}/>)}
 {[0,.25,.5,.75,1].map(f=>{const i=Math.round(f*(data.length-1));return <text key={f} x={x(i)} y={H-8} textAnchor={f===0?'start':f===1?'end':'middle'} fill="#8190a4" fontSize="11">{new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',hour:'numeric'}).format(new Date(data[i].time))}</text>})}
 {hover!=null&&<line x1={x(hover)} x2={x(hover)} y1={T} y2={H-B} stroke="#7c8da5" strokeDasharray="3 3"/>}
 </svg>:<div className="empty-chart">No matching observations in this period.<span>Missing data is never replaced with illustrative values.</span></div>}
 {item&&<div className="chart-tooltip"><strong>{ct(item.time,true)} · interval end</strong>{series.map(s=><div key={s.key}><span style={{color:s.color}}>{s.label}</span><b>{typeof item[s.key]==='number'?num((item[s.key] as number)/scale,2):'—'} {unit}</b></div>)}</div>}
 </div><div className="legend">{series.map(s=><span key={s.key}><i style={{background:s.color}} className={s.dash?'dashed':''}/>{s.label}</span>)}</div>
 <details className="chart-data"><summary>View chart data</summary><div className="table-scroll"><table><thead><tr><th>Interval end (CT)</th>{series.map(s=><th key={s.key}>{s.label} ({unit})</th>)}</tr></thead><tbody>{data.map(r=><tr key={r.time}><td>{ct(r.time,true)}</td>{series.map(s=><td key={s.key}>{typeof r[s.key]==='number'?num((r[s.key] as number)/scale,2):'—'}</td>)}</tr>)}</tbody></table></div></details></section>
}
function Stat({label,value,detail,accent='green',time}:{label:string;value:string;detail:string;accent?:string;time?:string|null}){return <div className={`stat ${accent}`}><span className="eyebrow">{label}</span><div className="stat-value">{value}</div><p>{detail}</p>{time&&<span className="stat-time">{ct(time,true)}</span>}</div>}
function Events({events}:{events:Event[]}){return <section className="panel"><div className="panel-head"><div><h2>Market event journal</h2><p>Threshold flags for research and case studies</p></div><span className="pill">{events.length} flags</span></div>{events.length?<div className="table-scroll"><table><thead><tr><th>Delivery interval</th><th>Signal</th><th>Deviation</th><th>Threshold</th></tr></thead><tbody>{events.slice(0,30).map((e,i)=><tr key={e.time+e.type+i}><td>{e.label}</td><td><span className="event-dot"/>{e.type}</td><td className={e.value>=0?'positive':'negative'}>{signed(e.value)} {e.unit}</td><td>±{num(e.threshold)} {e.unit}</td></tr>)}</tbody></table></div>:<div className="empty">No threshold flags in this period. This does not imply that every source is complete.</div>}</section>}
export default function Dashboard(){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[view,setView]=useState<View>('overview'),[range,setRange]=useState(48),[hub,setHub]=useState('HB_HOUSTON'),[city,setCity]=useState('Houston');
 const [error,setError]=useState(''),[loading,setLoading]=useState(true),[editions,setEditions]=useState<Edition[]>([]),[report,setReport]=useState<Report|null>(null),[selectedEdition,setSelectedEdition]=useState(''),[reportError,setReportError]=useState(''),[clock,setClock]=useState(Date.now());
 async function refresh(){setLoading(true);setError('');try{const r=await fetch(`${BASE}/data/latest.json`,{cache:'no-store'});if(!r.ok)throw new Error('Published snapshot is not yet available.');const s=await r.json();if(s.schema_version!==1||!Array.isArray(s.hours))throw new Error('Published data format could not be read.');setSnapshot(s);const index=await fetch(`${BASE}/data/reports.json`,{cache:'no-store'});if(index.ok){const list:Edition[]=await index.json();setEditions(list);if(list.length){setSelectedEdition(list[0].file);await loadReport(list[0].file)}}}catch(e){setError(e instanceof Error?e.message:'Unable to load published data.')}finally{setLoading(false)}}
 async function loadReport(file:string){setReportError('');setReport(null);try{const r=await fetch(`${BASE}/data/${file}`,{cache:'no-store'});if(!r.ok)throw new Error('This report is unavailable.');setReport(await r.json())}catch(e){setReportError(e instanceof Error?e.message:'Unable to load report.')}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>setClock(Date.now()),60000);return ()=>clearInterval(timer)},[]); // Refresh reloads published files, never calls source APIs.
 const hours=useMemo(()=>snapshot?.hours.filter(h=>new Date(h.time).getTime()>=new Date(snapshot.published_at).getTime()-range*3600000&&new Date(h.time).getTime()<=new Date(snapshot.published_at).getTime())||[],[snapshot,range]);
 const events=snapshot?.events.filter(e=>new Date(e.time).getTime()>=new Date(snapshot.published_at).getTime()-range*3600000)||[];
 const selectedHub=snapshot?.hubs.find(h=>h.hub===hub);
 const marketData:Datum[]=hours.map(h=>({time:h.time,dam:h.prices[hub]?.dam??null,rt:h.prices[hub]?.rt??null,spread:h.prices[hub]?.spread??null,basis:h.basis}));
 const loadData:Datum[]=hours.map(h=>({time:h.time,actual:h.load,forecast:h.load_forecast}));
 const windData:Datum[]=hours.map(h=>({time:h.time,actual:h.wind,forecast:h.wind_forecast}));
 const solarData:Datum[]=hours.map(h=>({time:h.time,actual:h.solar,forecast:h.solar_forecast}));
 const netData:Datum[]=hours.map(h=>({time:h.time,actual:h.net_load,forecast:h.net_load_forecast,error:h.net_load_error}));
 const pair:Series[]=[{key:'actual',label:'Actual',color:colors.green},{key:'forecast',label:'Prior-day expectation',color:colors.blue,dash:true}];
 const weather=snapshot?.weather.find(w=>w.city===city);
 const weatherData:Datum[]=(weather?.forecast||[]).filter(r=>new Date(r.time).getTime()>=clock&&new Date(r.time).getTime()<=clock+48*3600000).map(r=>({...r}));
 const priceDataAge=selectedHub?.time?Math.max(0,(clock-new Date(selectedHub.time).getTime())/3600000):null;
 const publicationAge=snapshot?(clock-new Date(snapshot.published_at).getTime())/3600000:0;
 const lastMatched=[...hours].reverse().find(h=>h.net_load_error!=null);
 const fmtGW=(r?:Reading)=>r?.value==null?'—':`${num(r.value/1000,2)} GW`;
 return <div className="shell"><aside className="sidebar"><a className="brand" href={`${BASE}/`}><span className="brand-mark">M<span/></span><div>ERCOT<span>MARKET MONITOR</span></div></a><div className="sidebar-label">RESEARCH WORKSPACE</div><nav aria-label="Dashboard views">{views.map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)} aria-current={view===id?'page':undefined}><Icon name={id}/>{label}{view===id&&<span className="nav-tick"/>}</button>)}</nav><div className="sidebar-note"><span className="signal-dot"/>PUBLIC MARKET RESEARCH<p>Official sources.<br/>Archived expectations.<br/>A clearer market picture.</p><a href="https://github.com/nikhilvinod23/ercot-market-dashboard/tree/ercot-market-monitoring" target="_blank" rel="noreferrer">Project on GitHub <Icon name="arrow"/></a></div><div className="sidebar-footer">TEXAS POWER MARKETS<span>Independent research · No affiliation with ERCOT</span></div></aside>
 <main><header className="topbar"><span>ERCOT <span className="separator">/</span> {views.find(v=>v[0]===view)?.[1]}</span><div><span className="snapshot-tag"><i/>Saved market snapshot</span><button className="icon-button" aria-label="Reload published snapshot" onClick={()=>void refresh()} disabled={loading}><Icon name="refresh"/></button></div></header>
 <div className="content"><div className="page-heading"><div><div className="eyebrow">TEXAS · ELECTRICITY · FUNDAMENTALS</div><h1>{views.find(v=>v[0]===view)?.[1]}</h1><p>{({overview:'Follow the market. Understand the surprise.',prices:'Where expectations meet real-time prices.',forecasts:'What ERCOT expected. What actually happened.',weather:'The atmospheric drivers behind load and renewables.',storage:'Watch the fleet respond to the market.',reports:'A record of the market, one edition at a time.',sources:'Every number has a source and a timestamp.'})[view]}</p></div><div className="publication"><span>PUBLISHED</span><strong>{ct(snapshot?.published_at,true)}</strong><small>{publicationAge>3?'This snapshot is older than 3 hours.':'Updates are collected separately from this page.'}</small></div></div>
 {error&&<div className="alert" role="alert">{error} {snapshot&&'The previously loaded snapshot remains visible.'}</div>}
 {!snapshot?<div className="loading-state"><span className="brand-mark">M</span><h2>{loading?'Loading the latest market edition…':'No published data available'}</h2><p>{loading?'Reading the saved public snapshot.':'Use the refresh control to retry. Source data is never simulated.'}</p></div>:<>
 {snapshot.sources.some(s=>s.status!=='ok')&&<div className="alert">{snapshot.sources.filter(s=>s.status!=='ok').length} sources were unavailable during collection. Available history remains visible. <button onClick={()=>setView('sources')}>View source status →</button></div>}
 {view!=='reports'&&view!=='sources'&&view!=='weather'&&<div className="controls"><div className="segmented" aria-label="Historical range">{[[24,'24 hours'],[48,'48 hours'],[168,'7 days']].map(([n,label])=><button key={n} className={range===n?'selected':''} aria-pressed={range===n} onClick={()=>setRange(Number(n))}>{label}</button>)}</div><span>All times Central · gaps indicate missing data</span><a className="text-link" href={`${BASE}/data/hourly.csv`} download><Icon name="download"/> Download data</a></div>}
 {view==='overview'&&<>
 <div className="stats-grid"><Stat label="SYSTEM DEMAND" value={fmtGW(snapshot.current.load)} detail="Latest observed system load" time={snapshot.current.load.time}/><Stat label="HOUSTON RT PRICE" value={money(snapshot.hubs[0]?.value)} detail={priceDataAge!=null&&priceDataAge>2?'Latest available · price data delayed':'15-minute settlement point price'} time={snapshot.hubs[0]?.time} accent="orange"/><Stat label="WIND GENERATION" value={fmtGW(snapshot.current.Wind)} detail="System-wide wind output" time={snapshot.current.Wind.time} accent="blue"/><Stat label="SOLAR GENERATION" value={fmtGW(snapshot.current.Solar)} detail="System-wide solar output" time={snapshot.current.Solar.time} accent="purple"/></div>
 <div className="secondary-stats"><div><span>NET LOAD</span><strong>{fmtGW(snapshot.current.net_load)}</strong><small>Demand − wind − solar · {ct(snapshot.current.net_load.time)}</small></div><div><span>NET LOAD SURPRISE</span><strong className={lastMatched?.net_load_error!=null&&lastMatched.net_load_error>=0?'positive':'negative'}>{lastMatched?signed(lastMatched.net_load_error!/1000,2)+' GW':'—'}</strong><small>Latest matched hour · {ct(lastMatched?.time)}</small></div><div><span>STORAGE NET OUTPUT</span><strong>{fmtGW(snapshot.current.net_storage)}</strong><small>Positive = discharging · {ct(snapshot.current.net_storage.time)}</small></div><div><span>ARCHIVED OBSERVATIONS</span><strong>{num(snapshot.archive_records,0)}</strong><small>Original values and forecast vintages</small></div></div>
 <div className="two-col"><Chart title="Demand & expectation" subtitle="Hourly observed load against the prior-day baseline" data={loadData} series={pair}/><Chart title="Houston price formation" subtitle="Hourly settlement prices · partial RT hours may be present" data={marketData} series={[{key:'rt',label:'Real-time',color:colors.orange},{key:'dam',label:'Day-ahead',color:colors.blue,dash:true}]} unit="$/MWh" scale={1}/></div>
 <div className="two-col"><Chart title="Net load" subtitle="Demand minus wind and solar generation" data={netData} series={pair}/><section className="panel"><div className="panel-head"><div><h2>Generation landscape</h2><p>Latest output by fuel · {ct(snapshot.generation[0]?.time)}</p></div><span className="unit">GW</span></div><div className="mix-bars">{snapshot.generation.map(g=><div key={g.fuel}><span>{g.fuel}</span><div className="mix-track"><i style={{width:`${Math.max(1,Math.abs(g.value)/Math.max(1,...snapshot.generation.map(g=>Math.abs(g.value)))*100)}%`,background:g.fuel==='Solar'?colors.purple:g.fuel==='Wind'?colors.blue:g.fuel==='Power Storage'?colors.orange:colors.green}}/></div><b>{num(g.value/1000,2)}</b></div>)}</div><p className="panel-footnote">Storage is net output; negative values indicate charging. Generation and load are distinct measures.</p></section></div><Events events={events}/>
 </>}
 {view==='prices'&&<><div className="selector-row"><label>SETTLEMENT POINT <select value={hub} onChange={e=>setHub(e.target.value)}>{snapshot.hubs.map(h=><option key={h.hub}>{h.hub}</option>)}</select></label><span className="pill">Trading hubs · settlement prices</span></div><div className="stats-grid"><Stat label="LATEST RT" value={money(selectedHub?.value)} detail="Native 15-minute interval" time={selectedHub?.time} accent="orange"/><Stat label="MATCHED DAM" value={money(selectedHub?.dam)} detail="Containing day-ahead hour" accent="blue"/><Stat label="RT − DAM" value={selectedHub?.spread==null?'—':signed(selectedHub.spread,2)+' $/MWh'} detail="Latest interval vs matched DAM"/><Stat label="PRICE FRESHNESS" value={priceDataAge==null?'—':num(priceDataAge,1)+' h'} detail={priceDataAge!=null&&priceDataAge>2?'Source history is delayed':'Age of latest price interval'} accent="purple"/></div><Chart title={`${hub.replace('HB_','')} · day-ahead vs real-time`} subtitle="RT is the mean of available 15-minute intervals; complete hours contain four" data={marketData} series={[{key:'rt',label:'Real-time mean',color:colors.orange},{key:'dam',label:'Day-ahead',color:colors.blue,dash:true}]} unit="$/MWh" scale={1}/><div className="two-col"><Chart title="RT − DAM spread" data={marketData} series={[{key:'spread',label:'Hourly spread',color:colors.orange}]} unit="$/MWh" scale={1}/><Chart title="West − Houston basis" subtitle="A geographic price difference; investigate constraints separately" data={marketData} series={[{key:'basis',label:'West less Houston',color:colors.purple}]} unit="$/MWh" scale={1}/></div><section className="panel"><div className="panel-head"><h2>Hub price board</h2><span className="unit">$/MWh</span></div><div className="table-scroll"><table><thead><tr><th>Settlement point</th><th>RT</th><th>Matched DAM</th><th>RT − DAM</th><th>RT interval end</th></tr></thead><tbody>{snapshot.hubs.map(h=><tr key={h.hub}><td>{h.hub}</td><td>{money(h.value)}</td><td>{money(h.dam)}</td><td className={h.spread!=null&&h.spread>=0?'positive':'negative'}>{signed(h.spread,2)}</td><td>{ct(h.time,true)}</td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-head"><div><h2>Tomorrow’s day-ahead curve</h2><p>Cleared DAM prices, where already published</p></div></div><Chart title="Forward DAM hours" data={snapshot.hours.filter(h=>new Date(h.time)>new Date(snapshot.published_at)&&h.prices[hub]?.dam!=null).map(h=>({time:h.time,dam:h.prices[hub]?.dam??null}))} series={[{key:'dam',label:'Day-ahead',color:colors.blue}]} unit="$/MWh" scale={1}/></section></>}
 {view==='forecasts'&&<><div className="callout"><span>THE CENTRAL QUESTION</span><p>Did unexpected demand or renewable output coincide with a change in real-time prices?</p><small>Baseline: latest source-posted forecast before the delivery day begins. Source-designated day-ahead series fill gaps where issue timestamps are unavailable.</small></div><div className="two-col"><Chart title="Demand forecast performance" data={loadData} series={pair}/><Chart title="Net load forecast performance" data={netData} series={pair}/><Chart title="Wind forecast performance" data={windData} series={pair}/><Chart title="Solar forecast performance" data={solarData} series={pair}/></div><Chart title="The net load surprise" subtitle="Actual net load minus expected net load; positive means a tighter balance than expected" data={netData} series={[{key:'error',label:'Net load error',color:colors.orange}]}/><section className="panel"><div className="panel-head"><div><h2>Matched forecast deviations</h2><p>Only compare the same delivery hour · values in GW</p></div></div><div className="table-scroll"><table><thead><tr><th>Interval end</th><th>Load error</th><th>Wind error</th><th>Solar error</th><th>Net load error</th><th>Houston RT − DAM</th></tr></thead><tbody>{[...hours].reverse().slice(0,48).map(h=><tr key={h.time}><td>{ct(h.time,true)}</td>{[h.load_error,h.wind_error,h.solar_error,h.net_load_error].map((v,i)=><td key={i}>{v==null?'—':signed(v/1000,2)}</td>)}<td>{signed(h.prices.HB_HOUSTON.spread,2)}</td></tr>)}</tbody></table></div></section><Chart title="Seven-day demand outlook" subtitle="Latest forecast version for each delivery hour; forecast revisions are archived" data={snapshot.hours.filter(h=>new Date(h.time)>new Date(snapshot.published_at)).map(h=>({time:h.time,load:h.load_outlook}))} series={[{key:'load',label:'Latest load forecast',color:colors.blue,dash:true}]}/><Events events={events}/></>}
 {view==='weather'&&<><div className="selector-row"><label>TEXAS LOCATION <select value={city} onChange={e=>setCity(e.target.value)}>{snapshot.weather.map(w=><option key={w.city}>{w.city}</option>)}</select></label><span className="pill">NOAA / National Weather Service</span></div><div className="stats-grid"><Stat label="TEMPERATURE" value={weather?.actual.temperature?.value==null?'—':num(weather.actual.temperature.value*9/5+32)+' °F'} detail="Latest station observation" time={weather?.actual.temperature?.time}/><Stat label="DEW POINT" value={weather?.actual.dew_point?.value==null?'—':num(weather.actual.dew_point.value*9/5+32)+' °F'} detail="Atmospheric moisture" accent="blue"/><Stat label="HUMIDITY" value={num(weather?.actual.humidity?.value)+' %'} detail="Relative humidity" accent="purple"/><Stat label="WIND SPEED" value={num(weather?.actual.wind_speed?.value)+' m/s'} detail="Station height, not turbine hub height" accent="orange"/></div><div className="two-col"><Chart title={`${city} · temperature outlook`} subtitle="Next 48 hours · independently issued weather forecasts" data={weatherData.map(r=>({...r,temperature:typeof r.temperature==='number'?r.temperature*9/5+32:null}))} series={[{key:'temperature',label:'Forecast temperature',color:colors.orange}]} unit="°F" scale={1}/><Chart title="Clouds & precipitation probability" subtitle="Cloud values span NWS grid intervals; rain values are hourly probabilities" data={weatherData} series={[{key:'cloud_cover',label:'Cloud cover',color:colors.blue},{key:'precip_probability',label:'Rain probability',color:colors.purple}]} unit="%" scale={1}/></div><section className="panel"><div className="panel-head"><h2>Regional weather observations</h2></div><div className="table-scroll"><table><thead><tr><th>Location</th><th>Temperature</th><th>Humidity</th><th>Wind</th><th>Observed</th></tr></thead><tbody>{snapshot.weather.map(w=><tr key={w.city}><td>{w.city}</td><td>{w.actual.temperature.value==null?'—':num(w.actual.temperature.value*9/5+32)+' °F'}</td><td>{num(w.actual.humidity.value)} %</td><td>{num(w.actual.wind_speed.value)} m/s</td><td>{ct(w.actual.temperature.time,true)}</td></tr>)}</tbody></table></div></section><div className="callout"><span>WEATHER → FUNDAMENTALS → PRICE</span><p>Temperature and humidity inform demand. Wind and clouds inform renewable supply. Their deviations change net load.</p><small>These are representative locations. Solar irradiance and turbine-height wind are not inferred from station readings.</small></div></>}
 {view==='storage'&&<><div className="stats-grid"><Stat label="NET STORAGE OUTPUT" value={fmtGW(snapshot.current.net_storage)} detail="Discharge less charging" time={snapshot.current.net_storage.time} accent="orange"/><Stat label="NET LOAD" value={fmtGW(snapshot.current.net_load)} detail="Co-temporal system observations"/><Stat label="HOUSTON RT" value={money(snapshot.hubs[0]?.value)} detail="Latest available price interval" accent="blue"/><Stat label="SOLAR OUTPUT" value={fmtGW(snapshot.current.Solar)} detail="Latest fleet generation" accent="purple"/></div><Chart title="Battery fleet behavior" subtitle="Charging is displayed as a positive magnitude; net output is signed" data={snapshot.storage.filter(r=>new Date(r.time).getTime()>=new Date(snapshot.published_at).getTime()-range*3600000)} series={[{key:'discharging',label:'Discharging',color:colors.orange},{key:'charging',label:'Charging',color:colors.blue},{key:'net_storage',label:'Net output',color:colors.green}]}/><div className="two-col"><Chart title="Solar production" data={solarData} series={[pair[0]]}/><Chart title="Houston RT price" data={marketData} series={[{key:'rt',label:'Hourly RT mean',color:colors.orange}]} unit="$/MWh" scale={1}/></div><div className="callout"><span>FROM OBSERVATION TO OPTIMIZATION</span><p>Explore fleet behavior first. Later, simulate a battery’s dispatch using forecasts, power limits, state of charge, efficiency, and degradation.</p><small>Public aggregate telemetry does not reveal individual battery state of charge or establish a profitable dispatch strategy.</small></div></>}
 {view==='reports'&&<><div className="selector-row"><label>REPORT EDITION <select value={selectedEdition} onChange={e=>{setSelectedEdition(e.target.value);void loadReport(e.target.value)}}>{editions.map(e=><option key={e.edition} value={e.file}>{ct(e.published_at,true)}</option>)}</select></label><div className="download-links"><a href={`${BASE}/data/latest-report.md`} download><Icon name="download"/>Latest written report</a><a href={`${BASE}/data/${selectedEdition}`} download><Icon name="download"/>Selected edition JSON</a></div></div>{reportError&&<div className="alert" role="alert">{reportError}</div>}{report?<><div className="report-header"><span className="eyebrow">PUBLIC MARKET LETTER</span><h2>{report.title}</h2><p>Edition published {ct(report.published_at,true)}</p></div>{[report.daily,report.weekly].map(s=><section className="panel report-panel" key={s.days}><div className="panel-head"><div><h2>{s.days===1?'Daily review':'Weekly review'}</h2><p>Trailing {s.days===1?'24 hours':'7 days'} through the edition cutoff</p></div><span className="pill">{s.complete_price_hours} complete price hours</span></div><div className="report-stats"><div><span>Average Houston RT</span><strong>{money(s.average_rt)}</strong></div><div><span>Highest Houston RT</span><strong>{money(s.max_rt)}</strong></div><div><span>Peak observed demand</span><strong>{s.peak_load==null?'—':num(s.peak_load/1000,2)+' GW'}</strong></div><div><span>Net load error MAE</span><strong>{s.net_load_mae==null?'—':num(s.net_load_mae/1000,2)+' GW'}</strong></div></div><p className="report-prose">{s.average_rt==null?'No complete Houston real-time price hours were available.':`Houston’s average real-time settlement price was ${money(s.average_rt)} per MWh across ${s.complete_price_hours} complete hours, reaching a maximum of ${money(s.max_rt)} per MWh.`} {s.peak_load!=null&&`Observed hourly demand peaked at ${num(s.peak_load/1000,2)} GW across ${s.observed_load_hours} load observations.`} {s.net_load_mae!=null&&`The mean absolute net load forecast deviation was ${num(s.net_load_mae/1000,2)} GW across ${s.forecast_comparison_hours} matched hours.`} {s.events} threshold flags were recorded.</p><small>Metrics describe available observations. Coverage counts matter when comparing editions.</small></section>)}<Events events={report.events}/><section className="panel"><div className="panel-head"><h2>Edition methodology</h2></div><div className="methods">{Object.entries(report.methodology).map(([k,v])=><p key={k}>{v}</p>)}</div></section></>:!reportError&&<div className="empty">Loading report edition…</div>}</>}
 {view==='sources'&&<><div className="callout"><span>FREE OFFICIAL SOURCES</span><p>ERCOT market and grid reports, plus NOAA weather. This public page reads saved files and keeps source credentials private.</p><small>Collection and publication are separate. Reloading the page retrieves the latest published edition.</small></div><section className="panel"><div className="panel-head"><div><h2>Collection status</h2><p>Status from the most recent collection attempt</p></div><span className="pill">{snapshot.sources.filter(s=>s.status==='ok').length} / {snapshot.sources.length} available</span></div><div className="table-scroll"><table><thead><tr><th>Source</th><th>Collection</th><th>Records</th><th>Source updated / checked</th></tr></thead><tbody>{snapshot.sources.map(s=><tr key={s.name}><td><a href={s.url} target="_blank" rel="noreferrer">{s.name} ↗</a>{s.message&&<small className="source-error">{s.message}</small>}</td><td><span className={`source-pill ${s.status==='ok'?'ok':'bad'}`}>{s.status==='ok'?'Available':'Unavailable'}</span></td><td>{num(s.records,0)}</td><td>{ct(s.updated||s.checked,true)}<small className="source-error">{s.updated?'Source timestamp':'Collection attempt timestamp'}</small></td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-head"><h2>Reading the dashboard</h2></div><div className="methods">{Object.entries(snapshot.methodology).map(([key,text])=><div key={key}><h3>{key.replaceAll('_',' ')}</h3><p>{text}</p></div>)}<h3>Collection and storage</h3><p>Python archives original responses and normalized observations. Forecast issue time, source publication time, and first collection time are separate. The free default archive is SQLite, preserved on the repository’s market-data branch. PostgreSQL can mirror the same records when configured.</p><h3>Publication</h3><p>Saved editions are published through GitHub Pages. Collection runs hourly on a best-effort schedule; daily, weekly, and manually triggered publishing are supported. The source archive retains normalized history, while this page displays a rolling window.</p><h3>Event thresholds</h3><p>Houston hourly RT − DAM: ±$50/MWh. Net load error: ±3 GW. Wind forecast error: ±2 GW. West − Houston basis: ±$50/MWh. These are exploratory flags, not price forecasts or trading recommendations.</p></div></section></>}
 <footer><span>ERCOT Market Monitor <i>·</i> Built for understanding the power market</span><a href="https://www.ercot.com" target="_blank" rel="noreferrer">ERCOT source ↗</a><a href={`${BASE}/data/latest.json`} download>Snapshot JSON ↓</a></footer>
 </>}
 </div></main></div>
}
